"""
setup_credentials.py
--------------------
One-time setup script. Run this ONCE to:
  1. Verify your private key connects to Polymarket
  2. Derive and save your L2 API credentials
  3. Check USDC balance and allowance
  4. Write credentials to .env

Usage:
  python setup_credentials.py
"""

import os
import sys
import json
from dotenv import load_dotenv, set_key

load_dotenv()

ENV_FILE = ".env"


def main():
    print("=" * 60)
    print("WeatherEdge Bot — Credential Setup")
    print("=" * 60)
    print()

    # ── Step 1: Get private key ──────────────────────────────────────────
    print("Step 1: Enter your Polymarket wallet private key.")
    print("  This is the private key from MetaMask or your web3 wallet.")
    print("  It starts with 0x and is 66 characters long.")
    print("  ⚠  Your key stays on your machine — it is never sent anywhere.")
    print()
    pk = input("Private key (0x...): ").strip()
    if not pk.startswith("0x") or len(pk) != 66:
        print("Error: Private key should start with 0x and be 66 chars.")
        sys.exit(1)

    # ── Step 2: Wallet address and funder ────────────────────────────────
    print()
    print("Step 2: Wallet type.")
    print("  (1) Standard MetaMask / EOA wallet  [most users]")
    print("  (2) Polymarket proxy wallet  [if you created via polymarket.com]")
    wallet_type = input("Enter 1 or 2: ").strip()
    if wallet_type == "2":
        sig_type = 2
        funder_address = input("Funder address (your main Polymarket address): ").strip()
    else:
        sig_type = 1
        funder_address = ""

    # ── Step 3: Derive API credentials ───────────────────────────────────
    print()
    print("Step 3: Connecting to Polymarket and deriving API credentials...")
    print("  (This requires py-clob-client: pip install py-clob-client)")
    print()

    try:
        from py_clob_client.client import ClobClient
    except ImportError:
        print("Error: py-clob-client not installed.")
        print("Run: pip install py-clob-client")
        sys.exit(1)

    try:
        client = ClobClient(
            host="https://clob.polymarket.com",
            key=pk,
            chain_id=137,
            signature_type=sig_type,
            funder=funder_address or None,
        )
        creds = client.create_or_derive_api_key()
        api_key        = creds.api_key
        api_secret     = creds.api_secret
        api_passphrase = creds.api_passphrase
        address        = client.get_address()
        print(f"  ✓ Connected! Address: {address}")
        print(f"  ✓ API Key:   {api_key}")

    except Exception as e:
        print(f"  Error: {e}")
        print()
        print("  Common fixes:")
        print("  - Check your private key is correct")
        print("  - If using proxy wallet, ensure funder address matches your Polymarket login")
        print("  - Try signature_type=0 if you're using a standard EOA")
        sys.exit(1)

    # ── Step 4: Check balance ─────────────────────────────────────────────
    print()
    print("Step 4: Checking USDC balance...")
    try:
        from py_clob_client.clob_types import BalanceAllowanceParams, AssetType
        client.set_api_creds(creds)
        balance_resp = client.get_balance_allowance(
            BalanceAllowanceParams(asset_type=AssetType.COLLATERAL)
        )
        balance = float(balance_resp.get("balance", 0))
        allowance = float(balance_resp.get("allowance", 0))
        print(f"  USDC Balance:   ${balance:.2f}")
        print(f"  CLOB Allowance: ${allowance:.2f}")

        if balance < 1.0:
            print()
            print("  ⚠  Balance is less than $1. Deposit USDC to Polygon before trading.")
            print("  You can deposit at: https://polymarket.com/profile")

        if allowance < 1.0:
            print()
            print("  ⚠  CLOB allowance is low. Approving...")
            client.update_balance_allowance(
                BalanceAllowanceParams(asset_type=AssetType.COLLATERAL)
            )
            print("  ✓ Allowance updated")

    except Exception as e:
        print(f"  Warning: Could not check balance ({e})")
        print("  This is non-fatal — you can still proceed.")

    # ── Step 5: Write .env ────────────────────────────────────────────────
    print()
    print("Step 5: Saving credentials to .env ...")

    env_content = f"""# WeatherEdge Bot — Polymarket Credentials
# Generated by setup_credentials.py
# ⚠  Keep this file private. Never commit it to git.

POLYMARKET_PRIVATE_KEY={pk}
POLYMARKET_API_KEY={api_key}
POLYMARKET_API_SECRET={api_secret}
POLYMARKET_API_PASSPHRASE={api_passphrase}
POLYMARKET_SIGNATURE_TYPE={sig_type}
POLYMARKET_FUNDER_ADDRESS={funder_address}
"""

    with open(ENV_FILE, "w") as f:
        f.write(env_content)

    print(f"  ✓ Credentials saved to {ENV_FILE}")
    print()
    print("=" * 60)
    print("Setup complete!")
    print()
    print("Next steps:")
    print("  Paper mode (test, no real money):")
    print("    python bot.py --mode paper --once")
    print()
    print("  Live mode (real trades):")
    print("    python bot.py --mode live")
    print()
    print("  Single city scan:")
    print("    python bot.py --mode paper --city new-york --event rain")
    print("=" * 60)


if __name__ == "__main__":
    main()
